on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  runtest: >-
    python3 -mvenv --system-site-packages /mnt/venv &&
    /mnt/venv/bin/pip install --upgrade wheel &&
    /mnt/venv/bin/pip install --upgrade pip &&
    /mnt/venv/bin/pip install '/mnt/app[test]' &&
    cd /mnt/app &&
    /mnt/venv/bin/python -munittest

  apt_setup: >-
    apt update && apt upgrade -y && apt install -y python3 sqlite3 python3-pip python3-venv

  dnf_setup: >-
    dnf update -y && dnf install -y python3 sqlite python3-pip

  apk_setup: >-
    apk update && apk upgrade && apk add python3 sqlite

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && 'testing' || '' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Python
          - image: docker.io/python:3.6
          - image: docker.io/python:3.7
          - image: docker.io/python:3.8
          - image: docker.io/python:3.9
          - image: docker.io/python:3.10
          - image: docker.io/python:3.11
          - image: docker.io/python:3.12
          - image: docker.io/python:3.13
          - image: docker.io/python:3.14

          # Debian
          - { image: "docker.io/debian:bullseye", setup: apt }
          - { image: "docker.io/debian:bookworm", setup: apt }
          - { image: "docker.io/debian:trixie", setup: apt }

          # Ubuntu
          - { image: "docker.io/ubuntu:20.04", setup: apt }
          - { image: "docker.io/ubuntu:22.04", setup: apt }
          - { image: "docker.io/ubuntu:24.04", setup: apt }

          # Fedora
          - { image: "docker.io/fedora:42", setup: dnf }
          - { image: "docker.io/fedora:43", setup: dnf }

          # RHEL (AlmaLinux)
          - { image: "docker.io/almalinux:8", setup: dnf }
          - { image: "docker.io/almalinux:9", setup: dnf }
          - { image: "docker.io/almalinux:10", setup: dnf }

          # CentOS Stream
          - { image: "quay.io/centos/centos:stream9", setup: dnf }
          - { image: "quay.io/centos/centos:stream10", setup: dnf }

          # Alpine
          - { image: "docker.io/alpine:3.20", setup: apk }
          - { image: "docker.io/alpine:3.21", setup: apk }
          - { image: "docker.io/alpine:3.22", setup: apk }
          - { image: "docker.io/alpine:3.23", setup: apk }

    name: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        env:
          SETUP: ${{ matrix.setup == 'apt' && env.apt_setup || matrix.setup == 'dnf' && env.dnf_setup || matrix.setup == 'apk' && env.apk_setup || '' }}
        run: |
          docker run --rm \
            -e PYTHONPATH=/mnt/app/src \
            -v "${{ github.workspace }}:/mnt/app:ro" \
            "${{ matrix.image }}" \
            /bin/sh -c "set -euxf; ${SETUP:+$SETUP &&} $runtest"
